# Generated by Django 5.1.5 on 2025-02-01 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='conteudo_video',
            field=models.FileField(upload_to='cursos/videos/'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='cursos.modulo'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='capa',
            field=models.ImageField(upload_to='cursos/capas/'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='cursos.curso'),
        ),
    ]
