# Generated by Django 5.1.5 on 2025-02-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_instrutor',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
